spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:./config/.env-${spring.profiles.active}[.properties]
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: ${SPRING.DATASOURCE.URL}
    driver-class-name: org.h2.Driver
    username: ${SPRING.DATASOURCE.USERNAME}
    password: ${SPRING.DATASOURCE.PASSWORD}
  h2:
    console:
      enabled: true
  application:
    name: monolith-ecommerce

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: monolith-ecommerce
    description: Monolith E-commerce Application
    version: 0.0.1
