spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:file:./configs/.env-${spring.profiles.active}[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: monolith-ecommerce

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#    env:
#      show-values: always
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: monolith-ecommerce
    description: Monolith E-commerce Application
    version: 0.0.1
